network:
  state_fc:
    - Linear:
        in_features: 17
        out_features: 512
      activation: ReLU
    - Linear:
        in_features: 512
        out_features: 1024
      activation: ReLU

  cnn:
    - Conv2d:
        in_channels: 4
        out_channels: 64
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 64
        out_channels: 128
        kernel_size: 3
        stride: 2
      activation: ReLU
    - MaxPool2d:
        kernel_size: 2
        stride: 2
    - Conv2d:
        in_channels: 128
        out_channels: 256
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 256
        out_channels: 512
        kernel_size: 3
        stride: 2
      activation: ReLU

  actor_fc:
    - Linear:
        in_features: 3072
        out_features: 1024
      activation: ReLU
    - Linear:
        in_features: 1024
        out_features: 512
      activation: ReLU
    - Linear:
        in_features: 512
        out_features: 2

  critic_fc:
    - Linear:
        in_features: 3072
        out_features: 1024
      activation: ReLU
    - Linear:
        in_features: 1024
        out_features: 512
      activation: ReLU
    - Linear:
        in_features: 512
        out_features: 1