network:
  state_fc:
    - Linear:
        in_features: 17
        out_features: 256
      activation: ReLU
    - Linear:
        in_features: 256
        out_features: 512
      activation: ReLU

  phys_encoder:
    - Conv2d:
        in_channels: 4
        out_channels: 16
        kernel_size: 5
        stride: 1
        padding: 2
    - BatchNorm2d:
        num_features: 16
      activation: ReLU
    - Conv2d:
        in_channels: 16
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
    - BatchNorm2d:
        num_features: 32
      activation: ReLU

  policy_cnn:
    - Conv2d:
        in_channels: 32
        out_channels: 64
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 64
        out_channels: 128
        kernel_size: 3
        stride: 2
      activation: ReLU
    - MaxPool2d:
        kernel_size: 2
        stride: 2
    - Conv2d:
        in_channels: 128
        out_channels: 256
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 256
        out_channels: 512
        kernel_size: 3
        stride: 2
      activation: ReLU

  actor_fc:
    - Linear:
        in_features: 1024
        out_features: 512
      activation: ReLU
    - Linear:
        in_features: 512
        out_features: 2

  action_encoder:
    - Linear:
        in_features: 2
        out_features: 64
    - Linear:
        in_features: 64
        out_features: 128
    - Linear:
        in_features: 128
        out_features: 256
    - Linear:
        in_features: 256
        out_features: 256
    - Linear: 
        in_features: 256
        out_features: 256
    - Linear:
        in_features: 256
        out_features: 512
    - Linear:
        in_features: 512
        out_features: 800

  motion_predictor:
    - Conv2d:
        in_channels: 32
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
    - BatchNorm2d:
        num_features: 32
      activation: ReLU
    - Conv2d:
        in_channels: 32
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
    - BatchNorm2d:
        num_features: 32
      activation: ReLU
    - Conv2d:
        in_channels: 32
        out_channels: 32
        kernel_size: 3
        stride: 1
        padding: 1
    - BatchNorm2d:
        num_features: 32
      activation: ReLU
    - Conv2d:
        in_channels: 32
        out_channels: 2
        kernel_size: 3
        stride: 1
        padding: 1

  critic_cnn:
    - Conv2d:
        in_channels: 4
        out_channels: 64
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 64
        out_channels: 128
        kernel_size: 3
        stride: 2
      activation: ReLU
    - MaxPool2d:
        kernel_size: 2
        stride: 2
    - Conv2d:
        in_channels: 128
        out_channels: 256
        kernel_size: 3
        stride: 2
      activation: ReLU
    - Conv2d:
        in_channels: 256
        out_channels: 512
        kernel_size: 3
        stride: 2
      activation: ReLU

  critic_fc:
    - Linear:
        in_features: 1024
        out_features: 512
      activation: ReLU
    - Linear:
        in_features: 512
        out_features: 1